In [ ]:
!pip install -q kagglehub

In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px
from textblob import TextBlob
import kagglehub

In [ ]:
path=kagglehub.dataset_download("shivamb/netflix-shows")
print("path to dataset files:",path)

Using Colab cache for faster access to the 'netflix-shows' dataset.
path to dataset files: /kaggle/input/netflix-shows

In [ ]:
df = pd.read_csv('/kaggle/input/netflix-shows/netflix_titles.csv')

In [ ]:
df.shape

(8807, 12)

In [ ]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [ ]:
x = df.groupby(['rating']).size().reset_index(name='counts')
print(x)

      rating  counts
0     66 min       1
1     74 min       1
2     84 min       1
3          G      41
4      NC-17       3
5         NR      80
6         PG     287
7      PG-13     490
8          R     799
9      TV-14    2160
10      TV-G     220
11     TV-MA    3207
12     TV-PG     863
13      TV-Y     307
14     TV-Y7     334
15  TV-Y7-FV       6
16        UR       3

In [ ]:
piechart = px.pie(x, values='counts', names='rating', title='Distribution of content rating on Netfilx')
piechart.show()

In [ ]:
x = df.groupby(['type']).size().reset_index(name='counts')
print(x)

      type  counts
0    Movie    6131
1  TV Show    2676

In [ ]:
x = df.groupby(['country']).size().reset_index(name='counts')
print(x)

                                               country  counts
0                                    , France, Algeria       1
1                                        , South Korea       1
2                                            Argentina      56
3    Argentina, Brazil, France, Poland, Germany, De...       1
4                                     Argentina, Chile       2
..                                                 ...     ...
743                                          Venezuela       1
744                                Venezuela, Colombia       1
745                                            Vietnam       7
746                                       West Germany       1
747                                           Zimbabwe       1

[748 rows x 2 columns]

In [ ]:
pichart = px.pie(x, values='counts', names='country', title='Netflix Shows by Country')
pichart.show()

In [ ]:
df['director']=df['director'].fillna('No Director Specified')

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,No Director Specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,No Director Specified,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,No Director Specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
directors_list = pd.DataFrame()
print(directors_list)

Empty DataFrame
Columns: []
Index: []

In [ ]:
directors_list = df['director'].str.split(',', expand=True).stack()
print(directors_list)

0     0          Kirsten Johnson
1     0    No Director Specified
2     0          Julien Leclercq
3     0    No Director Specified
4     0    No Director Specified
                   ...
8802  0            David Fincher
8803  0    No Director Specified
8804  0          Ruben Fleischer
8805  0             Peter Hewitt
8806  0              Mozez Singh
Length: 9612, dtype: object

In [ ]:
directors_list = directors_list.to_frame()
directors_list

                            0
0    0        Kirsten Johnson
1    0  No Director Specified
2    0        Julien Leclercq
3    0  No Director Specified
4    0  No Director Specified
...                       ...
8802 0          David Fincher
8803 0  No Director Specified
8804 0        Ruben Fleischer
8805 0           Peter Hewitt
8806 0            Mozez Singh

[9612 rows x 1 columns]

In [ ]:
directors_list.columns = ['director']
print(directors_list)

                     director
0    0        Kirsten Johnson
1    0  No Director Specified
2    0        Julien Leclercq
3    0  No Director Specified
4    0  No Director Specified
...                       ...
8802 0          David Fincher
8803 0  No Director Specified
8804 0        Ruben Fleischer
8805 0           Peter Hewitt
8806 0            Mozez Singh

[9612 rows x 1 columns]

In [ ]:
directors = directors_list.groupby(['director']).size().reset_index(name='Total count')
print(directors)

                       director  Total count
0                Aaron Moorhead            1
1                   Aaron Woolf            1
2      Abbas Alibhai Burmawalla            1
3              Abdullah Al Noor            1
4           Abhinav Shiv Tiwari            1
...                         ...          ...
5115                Çagan Irmak            1
5116           Ísold Uggadóttir            1
5117        Óskar Thór Axelsson            1
5118           Ömer Faruk Sorak            1
5119               Şenol Sönmez            1

[5120 rows x 2 columns]

In [ ]:
directors = directors[directors['director'] != "No Director specified"]

In [ ]:
print(directors)

                       director  Total count
0                Aaron Moorhead            1
1                   Aaron Woolf            1
2      Abbas Alibhai Burmawalla            1
3              Abdullah Al Noor            1
4           Abhinav Shiv Tiwari            1
...                         ...          ...
5115                Çagan Irmak            1
5116           Ísold Uggadóttir            1
5117        Óskar Thór Axelsson            1
5118           Ömer Faruk Sorak            1
5119               Şenol Sönmez            1

[5120 rows x 2 columns]

In [ ]:
directors = directors.sort_values(by=['Total Count'], ascending = False)
print(directors)

           Director  Total Count
4021  Rajiv Chilaka           22
261       Jan Suter           18
4068    Raúl Campos           18
3236   Marcus Raboy           16
4652    Suhas Kadav           16
...             ...          ...
3218    Marc Meyers            1
3217     Marc Levin            1
3216   Marc Francis            1
3215  Marc Fouchard            1
5014  Will Lovelace            1

[5120 rows x 2 columns]

In [ ]:
top4Directors = directors.head()
print(top4Directors)

                    director  Total count
0             Aaron Moorhead            1
1                Aaron Woolf            1
2   Abbas Alibhai Burmawalla            1
3           Abdullah Al Noor            1
4        Abhinav Shiv Tiwari            1

In [ ]:
top5Directors = top5Directors.sort_values(by=['Total Count'])
barChart = px.bar(top5Directors, x='Total Count', y = 'Director', title = 'Top 5 Directors on Netflix')
barChart.show()

In [ ]:
df['cast']=df['cast'].fillna('No cast specified')
cast_df = pd.DataFrame()
cast_df = df['cast'].str.split(',',expand=True).stack()
cast_df = cast_df.to_frame()
cast_df.columns = ['Actor']
actors = cast_df.groupby(['Actor']).size().reset_index(name = 'Total Count')
actors = actors[actors.Actor != 'No cast specified']
actors = actors.sort_values(by=['Total Count'], ascending=False)
top4Actors = actors.head()
top4Actors = top4Actors.sort_values(by=['Total Count'])
barChart2 = px.bar(top4Actors, x='Total Count', y='Actor', title='Top 4 Actors on Netflix')
barChart2.show()

In [ ]:
df1 = df[['type', 'release_year']]
df1 = df1.rename(columns = {"release_year":"Release Year", "type": "Type"})
df2 = df1.groupby(['Release Year', 'Type']).size().reset_index(name='Total Count')

In [ ]:
print(df2)

     Release Year     Type  Total Count
0            1925  TV Show            1
1            1942    Movie            2
2            1943    Movie            3
3            1944    Movie            3
4            1945    Movie            3
..            ...      ...          ...
114          2019  TV Show          397
115          2020    Movie          517
116          2020  TV Show          436
117          2021    Movie          277
118          2021  TV Show          315

[119 rows x 3 columns]

In [ ]:
  df2 =df2[df2['Release Year']>=2015]

In [ ]:
df2 = df2[df2['Release Year']>=2015]
graph = px.line(df2, x = "Release Year", y="Total Count", color = "Type", title = "Trend of Content Produced on Netfilx Every Year")
graph.show()

In [ ]:
df3 = df[['release_year', 'description']]
df3 = df3.rename(columns = {'release_year':'Release Year', 'description':'Description'})
for index, row in df3.iterrows():
  d=row['Description']
  testimonial = TextBlob(d)
  p = testimonial.sentiment.polarity
  if p==0:
    sent = 'Neutral'
  elif p>0:
    sent = 'Positive'
  else:
    sent = 'Negative'
  df3.loc[[index, 2], 'Sentiment']=sent

df3 = df3.groupby(['Release Year', 'Sentiment']).size().reset_index(name = 'Total Count')

df3 = df3[df3['Release Year']>2010]
barGraph = px.bar(df3, x="Release Year", y="Total Count", color = "Sentiment", title = "Sentiment Analysis of Content on Netflix")
barGraph.show()